apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: express-hello-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/aakashRajur/express-hello.git
---
